name: Java CI with Maven

on:
  workflow_dispatch
  # push:
  #   branches: [ master ] # Trigger on pushes to the master branch
  # pull_request:
  #   branches: [ master ] # Trigger on pull requests targeting the master branch

jobs:
  build:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
    - uses: actions/checkout@v5 # Checkout the repository code

    - name: Set up JDK 17 # Set up Java Development Kit
      uses: actions/setup-java@v5
      with:
        java-version: '17' # Specify the Java version
        distribution: 'temurin' # Choose a Java distribution (e.g., Temurin)
        cache: 'maven' # Cache Maven dependencies for faster builds

    - run: mvn --batch-mode --update-snapshots verify 
    - run: mkdir staging && cp  target/*.jar staging
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
         name:  hello-world-self-hosted
         path:  artifacts
