name: CI Pipeline

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]
    
  workflow_dispatch:

env:
  JAVA_VERSION: '11'

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ubuntu-latest, self-hosted-ci]
      fail-fast: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'maven'

    # Use regular Maven package instead of assembly:single
    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: List built artifacts
      run: ls -la target/

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact-name }}
        path: target/*.jar
        retention-days: 7
