name: CI/CD Pipeline using context

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Set up JDK 17
      uses: actions/setup-java@v5
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
    - run: mvn --batch-mode --update-snapshots verify 
    - run: mkdir staging && cp  target/*.jar staging
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
         name:  Package
         path:  staging
  deply-to-production:
    needs: build
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      - name: Deploy to Production
        run: |
          echo "Deploying to production on branch: ${{ github.ref }}"
          echo "Deploying to production by: ${{ github.actor }}"
